### ISSUE TITLE
make create-site return earlier

### ISSUE THREAD

**Issue by martinklepsch** [confetti-clj/confetti#16]
an improvement could be to check if only cloudfront is outstanding and exit at that point with a note that it may take up to 10 more minutes to have the distribution synced

Required for that is that is that outputs for stacks can be fetched before creation is fully done. 
Not sure if outputs are available before the stack is fully created.

Also cloudfront ID is a useful output value that most likely is not available before the distribution is fully created.

**Comment by martinklepsch** [comment]
There are no outputs at all available before cloudformation finishes.

**Comment by martinklepsch** [comment]
Another option could be splitting the `create-site` task into two pieces. One task creates the stack and puts a `stack-id.edn` file next to `build.boot`. Another task can then scan the root dir for these files and give a status report about the stack creation process. The second task can optionally block until stack creation is completed.

When a stack is fully created the second task should save all relevant information to another EDN file.

**Comment by podviaznikov** [comment]
I would suggest to print warning in the beginning of the task that it will take around 15 mins to create everything. In that way people would have right expectations

**Comment by martinklepsch** [comment]
A warning about the 15 min is in place, there now also is a task to fetch the stack outputs at a later point in time: 
https://github.com/confetti-clj/confetti/commit/c7dc64a43f49aa27c70ded226e2351f797942aff

**Comment by martinklepsch** [comment]
So the gist is `create-site` does not return earlier but there's an easy way out provided if it happens to take too long.
