### ISSUE TITLE
Problem creating site for root domain

### ISSUE THREAD

**Issue by podviaznikov** [confetti-clj/confetti#19]
I tried to use confetti for my clojurecup entry but hit following problem:
Tried to create site without dns (I wanted to use cloudflare). I used root domain (lifelines.io).
Got an error that it's not possible to create site for root domain without setting up dns.

Is this by design?

**Comment by martinklepsch** [comment]
Yes, see the readme. I'm thinking maybe a warning is enough though. There
are various ways to get root domain stuff working

**Comment by podviaznikov** [comment]
Got it. Now I see that in readme
