### ISSUE TITLE
Allow custom invalidation path for cloudfront

### ISSUE THREAD

**Issue by mynomoto** [confetti-clj/confetti#21]
Sometimes it may be better to invalidate `/*` than to invalidate many paths (costs maybe)

**Comment by martinklepsch** [comment]
@mynomoto is Amazon really billing only a single path if you supply a wildcard? They have the same work to do as if you supply all paths separately...

**Comment by mynomoto** [comment]
They say they do:
http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/Invalidation.html#invalidation-specifying-objects-paths

> The charge to submit an invalidation path is the same regardless of the number of objects you're invalidating: a single object (/images/logo.jpg) or all of the objects that are associated with a distribution (/*). For more information, see Amazon CloudFront Pricing.

It's not that important unless someone is generating html from templates and the base is always changing.

**Comment by martinklepsch** [comment]
@mynomoto a PR to supply a custom invalidation path via an option is welcome!
