### ISSUE TITLE
Exception while deploying a large number of files

### ISSUE THREAD

**Issue by arichiardi** [confetti-clj/confetti#22]
The title is actually an attempt to an explanation, but it can be something else.

The exception is the following:
```
Deploying on bucket devel.clojurescript.io...
Pack source files...
Sifting output files...

             clojure.lang.ExceptionInfo: java.lang.RuntimeException: Method code too large!, compiling:(NO_SOURCE_PATH:0:0)
    data: {:file "/tmp/boot.user8095246900604741649.clj", :line 67}
clojure.lang.Compiler$CompilerException: java.lang.RuntimeException: Method code too large!, compiling:(NO_SOURCE_PATH:0:0)
             java.lang.RuntimeException: Method code too large!
          clojure.asm.MethodWriter.getSize                 MethodWriter.java: 1872
       clojure.asm.ClassWriter.toByteArray                  ClassWriter.java:  775
                                       ...                                        
                         clojure.core/eval                          core.clj: 3081
                         boot.pod/eval-in*                           pod.clj:  437
                                       ...                                        
                         boot.pod/eval-in*                           pod.clj:  440
  confetti.boot-confetti/eval2817/fn/fn/fn                 boot_confetti.clj:  155
replumb.boot-pack-source/eval2560/fn/fn/fn              boot_pack_source.clj:   45
replumb.boot-pack-source/eval2606/fn/fn/fn              boot_pack_source.clj:   57
            boot.task.built-in/fn/fn/fn/fn                      built_in.clj:  416
               boot.user/eval3014/fn/fn/fn  boot.user8095246900604741649.clj:   45
                       boot.core/run-tasks                          core.clj:  927
                         boot.core/boot/fn                          core.clj:  937
       clojure.core/binding-conveyor-fn/fn                          core.clj: 1916
                                       ...                                        
```

I am basically including the following dependencies:
(def deps '[[org.clojure/clojurescript   "1.7.228"]
                  [org.clojure/core.async      "0.2.374"]
                  [reagent                     "0.5.1"]
                  [re-frame                    "0.5.0"]
                  [replumb/replumb             "0.2.2-SNAPSHOT"]
                  [org.clojure/tools.reader    "1.0.0-alpha3"]])

And the following task:
```
(core/deftask count-files
  []
  (core/with-pre-wrap fileset
    (util/warn "Fileset count %s" (count (tmpdir/ls fileset)))
    fileset))
```

I get `Fileset count 1704`. Maybe I am pushing it to the limit :smile:

**Comment by martinklepsch** [comment]
There's a send! function in boot that circumvents these method code limits.
We should probably use that.

**Comment by arichiardi** [comment]
I can do it, what is this send! about?

**Comment by arichiardi** [comment]
Ok I read the [issue](https://github.com/boot-clj/boot/issues/339) on Slack.
If I read the code correctly I should wrap [`(->str fmaps*)`](https://github.com/confetti-clj/confetti/blob/master/src/confetti/boot_confetti.clj#L157). Just wanted your ack, I will try anyways. :smile:

**Comment by martinklepsch** [comment]
Yes I think that should basically be it. Don't have the code in front of me
but sounds about right 👍

**Comment by arichiardi** [comment]
Thanks will try it out

**Comment by arichiardi** [comment]
Can I ask you why do you use bootlaces `0.1.14`? What bug does it solve that I am not aware of :smile:

**Comment by martinklepsch** [comment]
Huh, very valid question, 0.1.14 isn't even released so I probably used some fork locally. 0.1.13 should be fine 👍

**Comment by arichiardi** [comment]
Yeah I can patch that as well if you want :wink:

**Comment by martinklepsch** [comment]
sure go for it
