### ISSUE TITLE
The parameter previousObjectListing must be specified

### ISSUE THREAD

**Issue by arichiardi** [confetti-clj/confetti#24]
When I re-deploy something, and I actually don't know what triggers the error at the moment, I get:

```
                clojure.lang.ExceptionInfo: 
    data: {:file "/tmp/boot.user6757680306871265920.clj", :line 67}
java.lang.reflect.InvocationTargetException: 
         java.lang.IllegalArgumentException: The parameter previousObjectListing must be specified.
com.amazonaws.services.s3.model.ListNextBatchOfObjectsRequest.setPreviousObjectListing  ListNextBatchOfObjectsRequest.java:   51
                  com.amazonaws.services.s3.model.ListNextBatchOfObjectsRequest.<init>  ListNextBatchOfObjectsRequest.java:   33
```

Do you have some hint on how to debug it?

**Comment by martinklepsch** [comment]
I have now idea why this could be happening but it's coming from here:
https://github.com/confetti-clj/s3-deploy/blob/master/src/confetti/s3_deploy.clj#L29

Probably best to load that project in a repl and toy around with your particular bucket

**Comment by arichiardi** [comment]
Second execution gave no error, but it is probably wise to leave this open.

**Comment by martinklepsch** [comment]
@arichiardi moved to s3-deploy (see referenced issue)
