### ISSUE TITLE
Clarify Readme regarding access key

### ISSUE THREAD

**Issue by webappzero** [confetti-clj/confetti#37]
The Readme currently says

> Creating a site
> 
> Let's say you want to deploy a site at my-app.com. To create an S3 bucket, a CloudFront distribution and restricted access keys you can run the following:

This sounds like its saying that the access key and secret key will be created, but the function signature of `create-site` sounds like its expecting values for these options. I'm assuming I need to create an AWS user and create the access key ahead of time, so what does the Confetti Readme mean when it says it will create restricted access keys?

**Comment by martinklepsch** [comment]
Hey Jay, thanks for your comments!

Confetti requires an access/secret key pair to create all the necessary resources. One of these resources is a keypair that allows modifying the S3 bucket and invalidating Cloudfront caches. The idea behind this is that you can share this key with a friend/your team without giving access to the entirety of your AWS account.

So for the initial creation you could use your root keypair or similar and for anything beyond that you only need the generated keypair.

Does that make sense?

**Comment by webappzero** [comment]
Yes, upon reviewing the Readme with your comments in mind, it all makes sense to me now. Thank you, Martin!

It might be helpful to future readers to add the essence of your comments above to the Readme in the "Creating a site" section. Specifically, the need to use an account with admin privileges for the execution of `create-site`. What do you think?

**Comment by martinklepsch** [comment]
@webappzero just pushed a change for this, let me know if you have any other ideas how this could be communicated better?
